apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-test
  namespace: portainer
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-test
  namespace: portainer
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: portainer-test
  template:
    metadata:
      labels:
        app: portainer-test
    spec:
      serviceAccountName: portainer-sa-clusteradmin
      containers:
        - name: portainer
          image: portainerci/portainer-ee:pr-3800
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
            - containerPort: 9443
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: portainer-test
