---
- name: Install Go tools
  ansible.builtin.command: go install {{ item.pkg }}
  args:
    creates: "{{ ansible_env.HOME }}/go/bin/{{ item.bin }}"
  loop: "{{ go_tools }}"
  loop_control:
    label: "{{ item.bin }}"
