---
- name: Add Docker apt key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    architectures: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}"
    signed_by: /etc/apt/keyrings/docker.asc

- name: Install Docker Engine
  become: true
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: true

- name: Enable service docker
  become: true
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
