---
- name: Setup Portainer dev environment
  hosts: all
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin:{{ ansible_env.PATH }}"
  roles:
    - role: prerequisites
    - role: docker
    - role: golang
    - role: nodejs
    - role: git
    - role: gh
    - role: portainer_suite
